# Numpy

In [2]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])

In [6]:
print(a)

[1 2 3 4 5]


In [7]:
type(a)

numpy.ndarray

In [9]:
a2=np.array([[1,2,3],[4,5,6]])

In [10]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [11]:
a3=np.array([1,2,3],complex)

In [12]:
a3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
print(a2.ndim)

2


In [19]:
print(a3.itemsize)

16


In [20]:
print(a.dtype)

int32


In [21]:
print(a.size)

5


In [24]:
print(a3.shape)

(3,)


In [26]:
a.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [27]:
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
a=np.linspace(5,15,10)

In [29]:
a

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [30]:
a.max()

15.0

In [31]:
a.min()

5.0

In [32]:
a.sum()

100.0

In [3]:
import numpy as np
aa=np.array([1,2,3,4])
aa2=np.array([1,2,3,4])
print("addition=",aa+aa2)

addition= [2 4 6 8]


In [4]:
print("subtraction=",aa-aa2)

subtraction= [0 0 0 0]


In [5]:
print("multiplication=",aa*aa2)

multiplication= [ 1  4  9 16]


In [6]:
print("division=",aa/aa2)

division= [1. 1. 1. 1.]


In [7]:
print(np.vstack((aa,aa2)))

[[1 2 3 4]
 [1 2 3 4]]


In [8]:
print(np.hstack((aa,aa2)))

[1 2 3 4 1 2 3 4]


In [9]:
a = np.dtype(np.int32)  

In [10]:
a

dtype('int32')

In [14]:
arr = np.zeros((3,2), dtype = int) 
arr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [15]:
arr = np.ones((3,2), dtype = int)  
arr

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
l=[1,2,3,4]
arr1=np.asarray(l)
arr1

array([1, 2, 3, 4])

In [18]:
type(arr1)

numpy.ndarray

In [19]:
l = b'hello world'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [20]:
list = [0,2,4,6]  
it = iter(list)  
x = np.fromiter(it, dtype = float)  
print(x)  
print(type(x))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [21]:
arr = np.arange(0,10,2,float)  
arr

array([0., 2., 4., 6., 8.])

In [22]:
arr = np.linspace(10, 20, 5)  
print("The array over the given range is ",arr)  

The array over the given range is  [10.  12.5 15.  17.5 20. ]


In [23]:
arr = np.logspace(10, 20, num = 5, endpoint = True)  
print("The array over the given range is ",arr)  

The array over the given range is  [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


# Broadcasting

In [24]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)  
print("\nprinting array b..")  
print(b)  
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c)  


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


# Iterator

In [25]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing array:")  
print(a);  
print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ')  

Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [26]:
at=a.T

In [27]:
at

array([[ 1,  2, 10],
       [ 2,  4, 20],
       [ 3,  5, 39],
       [ 4,  6,  3]])

In [29]:
d=at.copy(order='C')

In [30]:
d

array([[ 1,  2, 10],
       [ 2,  4, 20],
       [ 3,  5, 39],
       [ 4,  6,  3]])

In [31]:
d=at.copy(order='F')

In [32]:
d

array([[ 1,  2, 10],
       [ 2,  4, 20],
       [ 3,  5, 39],
       [ 4,  6,  3]])

# Bitwise operator

In [33]:
a = 10  
b = 12  
  
print("binary representation of a:",bin(a))  
print("binary representation of b:",bin(b))  
print("Bitwise-and of a and b: ",np.bitwise_and(a,b))  

binary representation of a: 0b1010
binary representation of b: 0b1100
Bitwise-and of a and b:  8


In [34]:
import numpy as np  
  
a = 50  
b = 90  
print("binary representation of a:",bin(a))  
print("binary representation of b:",bin(b))  
print("Bitwise-or of a and b: ",np.bitwise_or(a,b))  

binary representation of a: 0b110010
binary representation of b: 0b1011010
Bitwise-or of a and b:  122


invert

In [35]:
arr = np.array([20],dtype = np.uint8)  
print("Binary representation:",np.binary_repr(20,8))  
  
print(np.invert(arr))  
  
print("Binary representation: ", np.binary_repr(235,8))  

Binary representation: 00010100
[235]
Binary representation:  11101011
